version: '3'
services:
  savycart-api:
    image: php:7.2-apache
    build: 
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - ${API_EXPOSED_PORT}:80
    volumes:
      - .:/var/www/html/sheiley-shop-api

  db:
    image: mysql:5.7
    volumes:
      - ./etc/db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_EXPOSED_PORT}:3306