version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./etc/sheiley_shop:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_EXPOSED_PORT}:3306
  sheiley-shop-api:
    build: .
    image: php:7.2-apache
    depends_on:
      - db
    ports:
      - ${API_EXPOSED_PORT}:80

volumes:
  mysqldata: