FROM php:7.2-apache

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git \
    zip \
    unzip
#Install PHP Extensions
RUN docker-php-ext-install pdo_mysql

RUN a2enmod rewrite

EXPOSE 80

WORKDIR /var/www/html/sheiley-shop-api