version: '3'
services:
  sheiley-shop-db:
    image: mysql:5.7
    volumes:
      - ./etc/db:/docker-entrypoint-initdb.d
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_EXPOSED_PORT}:3306
    networks:
      - traefik-network

  sheiley-shop-api:
    image: php:7.2-apache
    build: .
    depends_on:
      - sheiley-shop-db
    ports:
      - ${API_EXPOSED_PORT}:80
    labels: 
      - "traefik.http.routers.sheiley-shop-api.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.sheiley-shop-api.entrypoints=websecure"
      - "traefik.http.routers.sheiley-shop-api.tls.certresolver=myresolver"
    networks:
      - traefik-network

networks:
  traefik-network:
    external:
      name: traefik_proxynet
      
volumes:
  mysqldata: